[package]
name = "lowscript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gc = { version = "0.4", features = ["derive"] }
rustc-hash = "1.1.0"
indexmap = "1.8.1"
smallvec = "1.8.0"
